### ISSUE TITLE
how many epochs did you set when finetuning the model?

### ISSUE THREAD

**Issue by ahfyzzy** [SakuraRiven/CRAFT#2]
I want to reimplementing CRAFT , and found it taking too long to finetune the model. In config.py , the epoch is set to 400, so I want to know whether it's the configuration you used. 
BTW , could you tell me how long it took to finetune the model? And I feel kinda confused about the configuration 'cfg.ft.ratio_17' , it seems like you didn't use all the images in the train set of ICDAR17 when finetuning the model.

**Comment by SakuraRiven** [comment]
Maybe there are some bugs so I have to spend lots of epochs to find a good checkpoint. Actually, 100 epochs would not be much worse.
ratio_17 controls the mix ratio with icdar13. The merge dataset would be reset in each epoch so the icdar17 would be all used.

**Comment by ahfyzzy** [comment]
Thanks for your reply ! 
I'm working on the reimplement of CRAFT with LinkRefiner. Did you try to train CRAFT with CTW1500?

**Comment by SakuraRiven** [comment]
It is just a simple re-implementation when I was staging into OCR, so there is no extra experiments. This repo is just for reference.

**Comment by ahfyzzy** [comment]
Thanks for your patience!
Btw, is there any difference between ur net and the original one? I'm an amateur in deep learning...

**Comment by SakuraRiven** [comment]
This re-implementation keeps the same with original paper. But the official implementation uses another one [here](https://github.com/clovaai/CRAFT-pytorch/issues/24)
